version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd miniproject4-next
      - npm ci
  build:
    commands:
      - npm run build
      # 빌드 후 상위 디렉토리로 돌아와야 artifacts가 정상적으로 경로를 잡습니다.
      - cd ..

artifacts:
  files:
    - 'miniproject4-next/.next/**/*'
    - 'miniproject4-next/node_modules/**/*'
    - 'miniproject4-next/package.json'
    - 'appspec.yml'
    - 'miniproject4-next/next.config.mjs' # 설정 파일 추가
    - 'miniproject4-next/public/**/*'      # 이미지 등 정적 파일 추가
    - 'scripts/**/*'
  discard-paths: no # 폴더 구조 유지