version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  build:
    commands:
      - cd miniproject4-next
      - npm ci
      - npm run build

artifacts:
  base-directory: miniproject4-next
  files:
    - '**/*'